=begin
#Strava API v3

#Strava API

OpenAPI spec version: 3.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for StravaClient::AthletesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AthletesApi' do
  before do
    # run before each test
    @instance = StravaClient::AthletesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AthletesApi' do
    it 'should create an instance of AthletesApi' do
      expect(@instance).to be_instance_of(StravaClient::AthletesApi)
    end
  end

  # unit tests for get_logged_in_athlete
  # Get Authenticated Athlete
  # Returns the currently authenticated athlete.
  # @param [Hash] opts the optional parameters
  # @return [DetailedAthlete]
  describe 'get_logged_in_athlete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_logged_in_athlete_zones
  # Get Zones
  # Returns the the authenticated athlete&#39;s heart rate and power zones.
  # @param [Hash] opts the optional parameters
  # @return [Zones]
  describe 'get_logged_in_athlete_zones test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_stats
  # Get Athlete Stats
  # Returns the activity stats of an athlete.
  # @param id The identifier of the athlete.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page number.
  # @option opts [Integer] :per_page Number of items per page. Defaults to 30.
  # @return [ActivityStats]
  describe 'get_stats test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_logged_in_athlete
  # Update Athlete
  # Update the currently authenticated athlete.
  # @param body The athlete entity to update.
  # @param [Hash] opts the optional parameters
  # @return [DetailedAthlete]
  describe 'update_logged_in_athlete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
