=begin
#Strava API v3

#Strava API

OpenAPI spec version: 3.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for StravaClient::GearsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'GearsApi' do
  before do
    # run before each test
    @instance = StravaClient::GearsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GearsApi' do
    it 'should create an instance of GearsApi' do
      expect(@instance).to be_instance_of(StravaClient::GearsApi)
    end
  end

  # unit tests for get_gear_by_id
  # Get Equipment
  # Returns an equipment using its identifier.
  # @param id The identifier of the gear.
  # @param [Hash] opts the optional parameters
  # @return [DetailedGear]
  describe 'get_gear_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
