=begin
#Strava API v3

#Strava API

OpenAPI spec version: 3.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for StravaClient::RunningRacesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RunningRacesApi' do
  before do
    # run before each test
    @instance = StravaClient::RunningRacesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RunningRacesApi' do
    it 'should create an instance of RunningRacesApi' do
      expect(@instance).to be_instance_of(StravaClient::RunningRacesApi)
    end
  end

  # unit tests for get_running_race_by_id
  # Get Running Race
  # Returns a running race for a given identifier.
  # @param id The identifier of the running race.
  # @param [Hash] opts the optional parameters
  # @return [RunningRace]
  describe 'get_running_race_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_running_races
  # List Running Races
  # Returns a list running races based on a set of search criteria.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :year Filters the list by a given year.
  # @return [Array<RunningRace>]
  describe 'get_running_races test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
