=begin
#Strava API v3

#Strava API

OpenAPI spec version: 3.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for StravaClient::SegmentsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SegmentsApi' do
  before do
    # run before each test
    @instance = StravaClient::SegmentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SegmentsApi' do
    it 'should create an instance of SegmentsApi' do
      expect(@instance).to be_instance_of(StravaClient::SegmentsApi)
    end
  end

  # unit tests for explore_segments
  # Explore segments
  # Returns the segments matching a specified query.
  # @param bounds The geographical boundaries of the search.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :activity_type Desired activity type.
  # @option opts [Integer] :min_cat The minimum climbing category.
  # @option opts [Integer] :max_cat The maximum climbing category.
  # @return [ExplorerResponse]
  describe 'explore_segments test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_leaderboard_by_segment_id
  # Get Segment Leaderboard
  # Returns the specified segment leaderboard.
  # @param id The identifier of the segment leaderboard.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :gender Filter by gender.
  # @option opts [String] :age_group Premium Feature. Filter by age group.
  # @option opts [String] :weight_class Premium Feature. Filter by weight class.
  # @option opts [BOOLEAN] :following Filter by friends of the authenticated athlete.
  # @option opts [Integer] :club_id Filter by club.
  # @option opts [String] :date_range Filter by date range.
  # @option opts [Integer] :context_entries 
  # @option opts [Integer] :page Page number.
  # @option opts [Integer] :per_page Number of items per page. Defaults to 30.
  # @return [SegmentLeaderboard]
  describe 'get_leaderboard_by_segment_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_logged_in_athlete_starred_segments
  # List Starred Segments
  # List of the authenticated athlete&#39;s starred segments.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page number.
  # @option opts [Integer] :per_page Number of items per page. Defaults to 30.
  # @return [Array<SummarySegment>]
  describe 'get_logged_in_athlete_starred_segments test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_segment_by_id
  # Get Segment
  # Returns the specified segment.
  # @param id The identifier of the segment.
  # @param [Hash] opts the optional parameters
  # @return [DetailedSegment]
  describe 'get_segment_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for star_segment
  # Star Segment
  # Stars the given segment for the authenticated athlete.
  # @param id The identifier of the segment to star.
  # @param [Hash] opts the optional parameters
  # @return [DetailedSegment]
  describe 'star_segment test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
