=begin
#Strava API v3

#Strava API

OpenAPI spec version: 3.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for StravaClient::StreamsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'StreamsApi' do
  before do
    # run before each test
    @instance = StravaClient::StreamsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StreamsApi' do
    it 'should create an instance of StreamsApi' do
      expect(@instance).to be_instance_of(StravaClient::StreamsApi)
    end
  end

  # unit tests for get_activity_streams
  # Get Activity Streams
  # Returns the given activity&#39;s streams.
  # @param id The identifier of the activity.
  # @param keys Desired stream types.
  # @param key_by_type Must be true.
  # @param [Hash] opts the optional parameters
  # @return [StreamSet]
  describe 'get_activity_streams test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_segment_effort_streams
  # Get segment effort streams
  # Returns a set of streams for a segment effort completed by the authenticated athlete.
  # @param id The identifier of the segment effort.
  # @param keys The types of streams to return.
  # @param key_by_type Must be true.
  # @param [Hash] opts the optional parameters
  # @return [StreamSet]
  describe 'get_segment_effort_streams test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_segment_streams
  # Get Segment Streams
  # Returns the given segment&#39;s streams.
  # @param id The identifier of the segment.
  # @param keys The types of streams to return.
  # @param key_by_type Must be true.
  # @param [Hash] opts the optional parameters
  # @return [StreamSet]
  describe 'get_segment_streams test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
