=begin
#Strava API v3

#Strava API

OpenAPI spec version: 3.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for StravaClient::ExplorerResponse
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ExplorerResponse' do
  before do
    # run before each test
    @instance = StravaClient::ExplorerResponse.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ExplorerResponse' do
    it 'should create an instance of ExplorerResponse' do
      expect(@instance).to be_instance_of(StravaClient::ExplorerResponse)
    end
  end
  describe 'test attribute "segments"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

