=begin
#Strava API v3

#Strava API

OpenAPI spec version: 3.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for StravaClient::LatLng
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'LatLng' do
  before do
    # run before each test
    @instance = StravaClient::LatLng.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LatLng' do
    it 'should create an instance of LatLng' do
      expect(@instance).to be_instance_of(StravaClient::LatLng)
    end
  end
end

