=begin
#Strava API v3

#Strava API

OpenAPI spec version: 3.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'date'

module StravaClient
  # A set of rolled-up statistics and totals for an athlete
  class ActivityStats
    # The longest distance ridden by the athlete.
    attr_accessor :biggest_ride_distance

    # The highest climb ridden by the athlete.
    attr_accessor :biggest_climb_elevation_gain

    attr_accessor :recent_ride_totals

    attr_accessor :recent_run_totals

    attr_accessor :recent_swim_totals

    attr_accessor :ytd_ride_totals

    attr_accessor :ytd_run_totals

    attr_accessor :ytd_swim_totals

    attr_accessor :all_ride_totals

    attr_accessor :all_run_totals

    attr_accessor :all_swim_totals


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'biggest_ride_distance' => :'biggest_ride_distance',
        :'biggest_climb_elevation_gain' => :'biggest_climb_elevation_gain',
        :'recent_ride_totals' => :'recent_ride_totals',
        :'recent_run_totals' => :'recent_run_totals',
        :'recent_swim_totals' => :'recent_swim_totals',
        :'ytd_ride_totals' => :'ytd_ride_totals',
        :'ytd_run_totals' => :'ytd_run_totals',
        :'ytd_swim_totals' => :'ytd_swim_totals',
        :'all_ride_totals' => :'all_ride_totals',
        :'all_run_totals' => :'all_run_totals',
        :'all_swim_totals' => :'all_swim_totals'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'biggest_ride_distance' => :'Float',
        :'biggest_climb_elevation_gain' => :'Float',
        :'recent_ride_totals' => :'ActivityTotal',
        :'recent_run_totals' => :'ActivityTotal',
        :'recent_swim_totals' => :'ActivityTotal',
        :'ytd_ride_totals' => :'ActivityTotal',
        :'ytd_run_totals' => :'ActivityTotal',
        :'ytd_swim_totals' => :'ActivityTotal',
        :'all_ride_totals' => :'ActivityTotal',
        :'all_run_totals' => :'ActivityTotal',
        :'all_swim_totals' => :'ActivityTotal'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'biggest_ride_distance')
        self.biggest_ride_distance = attributes[:'biggest_ride_distance']
      end

      if attributes.has_key?(:'biggest_climb_elevation_gain')
        self.biggest_climb_elevation_gain = attributes[:'biggest_climb_elevation_gain']
      end

      if attributes.has_key?(:'recent_ride_totals')
        self.recent_ride_totals = attributes[:'recent_ride_totals']
      end

      if attributes.has_key?(:'recent_run_totals')
        self.recent_run_totals = attributes[:'recent_run_totals']
      end

      if attributes.has_key?(:'recent_swim_totals')
        self.recent_swim_totals = attributes[:'recent_swim_totals']
      end

      if attributes.has_key?(:'ytd_ride_totals')
        self.ytd_ride_totals = attributes[:'ytd_ride_totals']
      end

      if attributes.has_key?(:'ytd_run_totals')
        self.ytd_run_totals = attributes[:'ytd_run_totals']
      end

      if attributes.has_key?(:'ytd_swim_totals')
        self.ytd_swim_totals = attributes[:'ytd_swim_totals']
      end

      if attributes.has_key?(:'all_ride_totals')
        self.all_ride_totals = attributes[:'all_ride_totals']
      end

      if attributes.has_key?(:'all_run_totals')
        self.all_run_totals = attributes[:'all_run_totals']
      end

      if attributes.has_key?(:'all_swim_totals')
        self.all_swim_totals = attributes[:'all_swim_totals']
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          biggest_ride_distance == o.biggest_ride_distance &&
          biggest_climb_elevation_gain == o.biggest_climb_elevation_gain &&
          recent_ride_totals == o.recent_ride_totals &&
          recent_run_totals == o.recent_run_totals &&
          recent_swim_totals == o.recent_swim_totals &&
          ytd_ride_totals == o.ytd_ride_totals &&
          ytd_run_totals == o.ytd_run_totals &&
          ytd_swim_totals == o.ytd_swim_totals &&
          all_ride_totals == o.all_ride_totals &&
          all_run_totals == o.all_run_totals &&
          all_swim_totals == o.all_swim_totals
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [biggest_ride_distance, biggest_climb_elevation_gain, recent_ride_totals, recent_run_totals, recent_swim_totals, ytd_ride_totals, ytd_run_totals, ytd_swim_totals, all_ride_totals, all_run_totals, all_swim_totals].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = StravaClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
