=begin
#Strava API v3

#The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.

The version of the OpenAPI document: 3.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'date'
require 'time'

module StravaClient
  class DetailedAthlete
    # The unique identifier of the athlete
    attr_accessor :id

    # Resource state, indicates level of detail. Possible values: 1 -> \"meta\", 2 -> \"summary\", 3 -> \"detail\"
    attr_accessor :resource_state

    # The athlete's first name.
    attr_accessor :firstname

    # The athlete's last name.
    attr_accessor :lastname

    # URL to a 62x62 pixel profile picture.
    attr_accessor :profile_medium

    # URL to a 124x124 pixel profile picture.
    attr_accessor :profile

    # The athlete's city.
    attr_accessor :city

    # The athlete's state or geographical region.
    attr_accessor :state

    # The athlete's country.
    attr_accessor :country

    # The athlete's sex.
    attr_accessor :sex

    # Deprecated.  Use summit field instead. Whether the athlete has any Summit subscription.
    attr_accessor :premium

    # Whether the athlete has any Summit subscription.
    attr_accessor :summit

    # The time at which the athlete was created.
    attr_accessor :created_at

    # The time at which the athlete was last updated.
    attr_accessor :updated_at

    # The athlete's follower count.
    attr_accessor :follower_count

    # The athlete's friend count.
    attr_accessor :friend_count

    # The athlete's preferred unit system.
    attr_accessor :measurement_preference

    # The athlete's FTP (Functional Threshold Power).
    attr_accessor :ftp

    # The athlete's weight.
    attr_accessor :weight

    # The athlete's clubs.
    attr_accessor :clubs

    # The athlete's bikes.
    attr_accessor :bikes

    # The athlete's shoes.
    attr_accessor :shoes

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'resource_state' => :'resource_state',
        :'firstname' => :'firstname',
        :'lastname' => :'lastname',
        :'profile_medium' => :'profile_medium',
        :'profile' => :'profile',
        :'city' => :'city',
        :'state' => :'state',
        :'country' => :'country',
        :'sex' => :'sex',
        :'premium' => :'premium',
        :'summit' => :'summit',
        :'created_at' => :'created_at',
        :'updated_at' => :'updated_at',
        :'follower_count' => :'follower_count',
        :'friend_count' => :'friend_count',
        :'measurement_preference' => :'measurement_preference',
        :'ftp' => :'ftp',
        :'weight' => :'weight',
        :'clubs' => :'clubs',
        :'bikes' => :'bikes',
        :'shoes' => :'shoes'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'Integer',
        :'resource_state' => :'Integer',
        :'firstname' => :'String',
        :'lastname' => :'String',
        :'profile_medium' => :'String',
        :'profile' => :'String',
        :'city' => :'String',
        :'state' => :'String',
        :'country' => :'String',
        :'sex' => :'String',
        :'premium' => :'Boolean',
        :'summit' => :'Boolean',
        :'created_at' => :'Time',
        :'updated_at' => :'Time',
        :'follower_count' => :'Integer',
        :'friend_count' => :'Integer',
        :'measurement_preference' => :'String',
        :'ftp' => :'Integer',
        :'weight' => :'Float',
        :'clubs' => :'Array<SummaryClub>',
        :'bikes' => :'Array<SummaryGear>',
        :'shoes' => :'Array<SummaryGear>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # List of class defined in allOf (OpenAPI v3)
    def self.openapi_all_of
      [
      :'SummaryAthlete'
      ]
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `StravaClient::DetailedAthlete` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `StravaClient::DetailedAthlete`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'resource_state')
        self.resource_state = attributes[:'resource_state']
      end

      if attributes.key?(:'firstname')
        self.firstname = attributes[:'firstname']
      end

      if attributes.key?(:'lastname')
        self.lastname = attributes[:'lastname']
      end

      if attributes.key?(:'profile_medium')
        self.profile_medium = attributes[:'profile_medium']
      end

      if attributes.key?(:'profile')
        self.profile = attributes[:'profile']
      end

      if attributes.key?(:'city')
        self.city = attributes[:'city']
      end

      if attributes.key?(:'state')
        self.state = attributes[:'state']
      end

      if attributes.key?(:'country')
        self.country = attributes[:'country']
      end

      if attributes.key?(:'sex')
        self.sex = attributes[:'sex']
      end

      if attributes.key?(:'premium')
        self.premium = attributes[:'premium']
      end

      if attributes.key?(:'summit')
        self.summit = attributes[:'summit']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end

      if attributes.key?(:'follower_count')
        self.follower_count = attributes[:'follower_count']
      end

      if attributes.key?(:'friend_count')
        self.friend_count = attributes[:'friend_count']
      end

      if attributes.key?(:'measurement_preference')
        self.measurement_preference = attributes[:'measurement_preference']
      end

      if attributes.key?(:'ftp')
        self.ftp = attributes[:'ftp']
      end

      if attributes.key?(:'weight')
        self.weight = attributes[:'weight']
      end

      if attributes.key?(:'clubs')
        if (value = attributes[:'clubs']).is_a?(Array)
          self.clubs = value
        end
      end

      if attributes.key?(:'bikes')
        if (value = attributes[:'bikes']).is_a?(Array)
          self.bikes = value
        end
      end

      if attributes.key?(:'shoes')
        if (value = attributes[:'shoes']).is_a?(Array)
          self.shoes = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      sex_validator = EnumAttributeValidator.new('String', ["M", "F"])
      return false unless sex_validator.valid?(@sex)
      measurement_preference_validator = EnumAttributeValidator.new('String', ["feet", "meters"])
      return false unless measurement_preference_validator.valid?(@measurement_preference)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] sex Object to be assigned
    def sex=(sex)
      validator = EnumAttributeValidator.new('String', ["M", "F"])
      unless validator.valid?(sex)
        fail ArgumentError, "invalid value for \"sex\", must be one of #{validator.allowable_values}."
      end
      @sex = sex
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] measurement_preference Object to be assigned
    def measurement_preference=(measurement_preference)
      validator = EnumAttributeValidator.new('String', ["feet", "meters"])
      unless validator.valid?(measurement_preference)
        fail ArgumentError, "invalid value for \"measurement_preference\", must be one of #{validator.allowable_values}."
      end
      @measurement_preference = measurement_preference
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          resource_state == o.resource_state &&
          firstname == o.firstname &&
          lastname == o.lastname &&
          profile_medium == o.profile_medium &&
          profile == o.profile &&
          city == o.city &&
          state == o.state &&
          country == o.country &&
          sex == o.sex &&
          premium == o.premium &&
          summit == o.summit &&
          created_at == o.created_at &&
          updated_at == o.updated_at &&
          follower_count == o.follower_count &&
          friend_count == o.friend_count &&
          measurement_preference == o.measurement_preference &&
          ftp == o.ftp &&
          weight == o.weight &&
          clubs == o.clubs &&
          bikes == o.bikes &&
          shoes == o.shoes
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, resource_state, firstname, lastname, profile_medium, profile, city, state, country, sex, premium, summit, created_at, updated_at, follower_count, friend_count, measurement_preference, ftp, weight, clubs, bikes, shoes].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = StravaClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
