=begin
#Strava API v3

#The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.

The version of the OpenAPI document: 3.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'date'
require 'time'

module StravaClient
  class Route
    attr_accessor :athlete

    # The description of the route
    attr_accessor :description

    # The route's distance, in meters
    attr_accessor :distance

    # The route's elevation gain.
    attr_accessor :elevation_gain

    # The unique identifier of this route
    attr_accessor :id

    # The unique identifier of the route in string format
    attr_accessor :id_str

    attr_accessor :map

    # The name of this route
    attr_accessor :name

    # Whether this route is private
    attr_accessor :private

    # Whether this route is starred by the logged-in athlete
    attr_accessor :starred

    # An epoch timestamp of when the route was created
    attr_accessor :timestamp

    # This route's type (1 for ride, 2 for runs)
    attr_accessor :type

    # This route's sub-type (1 for road, 2 for mountain bike, 3 for cross, 4 for trail, 5 for mixed)
    attr_accessor :sub_type

    # The time at which the route was created
    attr_accessor :created_at

    # The time at which the route was last updated
    attr_accessor :updated_at

    # Estimated time in seconds for the authenticated athlete to complete route
    attr_accessor :estimated_moving_time

    # The segments traversed by this route
    attr_accessor :segments

    # The custom waypoints along this route
    attr_accessor :waypoints

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'athlete' => :'athlete',
        :'description' => :'description',
        :'distance' => :'distance',
        :'elevation_gain' => :'elevation_gain',
        :'id' => :'id',
        :'id_str' => :'id_str',
        :'map' => :'map',
        :'name' => :'name',
        :'private' => :'private',
        :'starred' => :'starred',
        :'timestamp' => :'timestamp',
        :'type' => :'type',
        :'sub_type' => :'sub_type',
        :'created_at' => :'created_at',
        :'updated_at' => :'updated_at',
        :'estimated_moving_time' => :'estimated_moving_time',
        :'segments' => :'segments',
        :'waypoints' => :'waypoints'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'athlete' => :'SummaryAthlete',
        :'description' => :'String',
        :'distance' => :'Float',
        :'elevation_gain' => :'Float',
        :'id' => :'Integer',
        :'id_str' => :'String',
        :'map' => :'PolylineMap',
        :'name' => :'String',
        :'private' => :'Boolean',
        :'starred' => :'Boolean',
        :'timestamp' => :'Integer',
        :'type' => :'Integer',
        :'sub_type' => :'Integer',
        :'created_at' => :'Time',
        :'updated_at' => :'Time',
        :'estimated_moving_time' => :'Integer',
        :'segments' => :'Array<SummarySegment>',
        :'waypoints' => :'Array<Waypoint>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `StravaClient::Route` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `StravaClient::Route`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'athlete')
        self.athlete = attributes[:'athlete']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'distance')
        self.distance = attributes[:'distance']
      end

      if attributes.key?(:'elevation_gain')
        self.elevation_gain = attributes[:'elevation_gain']
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'id_str')
        self.id_str = attributes[:'id_str']
      end

      if attributes.key?(:'map')
        self.map = attributes[:'map']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'private')
        self.private = attributes[:'private']
      end

      if attributes.key?(:'starred')
        self.starred = attributes[:'starred']
      end

      if attributes.key?(:'timestamp')
        self.timestamp = attributes[:'timestamp']
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      end

      if attributes.key?(:'sub_type')
        self.sub_type = attributes[:'sub_type']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end

      if attributes.key?(:'estimated_moving_time')
        self.estimated_moving_time = attributes[:'estimated_moving_time']
      end

      if attributes.key?(:'segments')
        if (value = attributes[:'segments']).is_a?(Array)
          self.segments = value
        end
      end

      if attributes.key?(:'waypoints')
        if (value = attributes[:'waypoints']).is_a?(Array)
          self.waypoints = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@waypoints.nil? && @waypoints.length < 0
        invalid_properties.push('invalid value for "waypoints", number of items must be greater than or equal to 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@waypoints.nil? && @waypoints.length < 0
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] waypoints Value to be assigned
    def waypoints=(waypoints)
      if waypoints.nil?
        fail ArgumentError, 'waypoints cannot be nil'
      end

      if waypoints.length < 0
        fail ArgumentError, 'invalid value for "waypoints", number of items must be greater than or equal to 0.'
      end

      @waypoints = waypoints
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          athlete == o.athlete &&
          description == o.description &&
          distance == o.distance &&
          elevation_gain == o.elevation_gain &&
          id == o.id &&
          id_str == o.id_str &&
          map == o.map &&
          name == o.name &&
          private == o.private &&
          starred == o.starred &&
          timestamp == o.timestamp &&
          type == o.type &&
          sub_type == o.sub_type &&
          created_at == o.created_at &&
          updated_at == o.updated_at &&
          estimated_moving_time == o.estimated_moving_time &&
          segments == o.segments &&
          waypoints == o.waypoints
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [athlete, description, distance, elevation_gain, id, id_str, map, name, private, starred, timestamp, type, sub_type, created_at, updated_at, estimated_moving_time, segments, waypoints].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = StravaClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
