=begin
#Strava API v3

#The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.

The version of the OpenAPI document: 3.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'date'
require 'time'

module StravaClient
  class SportType
    ALPINE_SKI = "AlpineSki".freeze
    BACKCOUNTRY_SKI = "BackcountrySki".freeze
    BADMINTON = "Badminton".freeze
    CANOEING = "Canoeing".freeze
    CROSSFIT = "Crossfit".freeze
    E_BIKE_RIDE = "EBikeRide".freeze
    ELLIPTICAL = "Elliptical".freeze
    E_MOUNTAIN_BIKE_RIDE = "EMountainBikeRide".freeze
    GOLF = "Golf".freeze
    GRAVEL_RIDE = "GravelRide".freeze
    HANDCYCLE = "Handcycle".freeze
    HIGH_INTENSITY_INTERVAL_TRAINING = "HighIntensityIntervalTraining".freeze
    HIKE = "Hike".freeze
    ICE_SKATE = "IceSkate".freeze
    INLINE_SKATE = "InlineSkate".freeze
    KAYAKING = "Kayaking".freeze
    KITESURF = "Kitesurf".freeze
    MOUNTAIN_BIKE_RIDE = "MountainBikeRide".freeze
    NORDIC_SKI = "NordicSki".freeze
    PICKLEBALL = "Pickleball".freeze
    PILATES = "Pilates".freeze
    RACQUETBALL = "Racquetball".freeze
    RIDE = "Ride".freeze
    ROCK_CLIMBING = "RockClimbing".freeze
    ROLLER_SKI = "RollerSki".freeze
    ROWING = "Rowing".freeze
    RUN = "Run".freeze
    SAIL = "Sail".freeze
    SKATEBOARD = "Skateboard".freeze
    SNOWBOARD = "Snowboard".freeze
    SNOWSHOE = "Snowshoe".freeze
    SOCCER = "Soccer".freeze
    SQUASH = "Squash".freeze
    STAIR_STEPPER = "StairStepper".freeze
    STAND_UP_PADDLING = "StandUpPaddling".freeze
    SURFING = "Surfing".freeze
    SWIM = "Swim".freeze
    TABLE_TENNIS = "TableTennis".freeze
    TENNIS = "Tennis".freeze
    TRAIL_RUN = "TrailRun".freeze
    VELOMOBILE = "Velomobile".freeze
    VIRTUAL_RIDE = "VirtualRide".freeze
    VIRTUAL_ROW = "VirtualRow".freeze
    VIRTUAL_RUN = "VirtualRun".freeze
    WALK = "Walk".freeze
    WEIGHT_TRAINING = "WeightTraining".freeze
    WHEELCHAIR = "Wheelchair".freeze
    WINDSURF = "Windsurf".freeze
    WORKOUT = "Workout".freeze
    YOGA = "Yoga".freeze

    def self.all_vars
      @all_vars ||= [ALPINE_SKI, BACKCOUNTRY_SKI, BADMINTON, CANOEING, CROSSFIT, E_BIKE_RIDE, ELLIPTICAL, E_MOUNTAIN_BIKE_RIDE, GOLF, GRAVEL_RIDE, HANDCYCLE, HIGH_INTENSITY_INTERVAL_TRAINING, HIKE, ICE_SKATE, INLINE_SKATE, KAYAKING, KITESURF, MOUNTAIN_BIKE_RIDE, NORDIC_SKI, PICKLEBALL, PILATES, RACQUETBALL, RIDE, ROCK_CLIMBING, ROLLER_SKI, ROWING, RUN, SAIL, SKATEBOARD, SNOWBOARD, SNOWSHOE, SOCCER, SQUASH, STAIR_STEPPER, STAND_UP_PADDLING, SURFING, SWIM, TABLE_TENNIS, TENNIS, TRAIL_RUN, VELOMOBILE, VIRTUAL_RIDE, VIRTUAL_ROW, VIRTUAL_RUN, WALK, WEIGHT_TRAINING, WHEELCHAIR, WINDSURF, WORKOUT, YOGA].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if SportType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #SportType"
    end
  end
end
