=begin
#Strava API v3

#The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.

The version of the OpenAPI document: 3.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'date'
require 'time'

module StravaClient
  class SummaryClub
    # The club's unique identifier.
    attr_accessor :id

    # Resource state, indicates level of detail. Possible values: 1 -> \"meta\", 2 -> \"summary\", 3 -> \"detail\"
    attr_accessor :resource_state

    # The club's name.
    attr_accessor :name

    # URL to a 60x60 pixel profile picture.
    attr_accessor :profile_medium

    # URL to a ~1185x580 pixel cover photo.
    attr_accessor :cover_photo

    # URL to a ~360x176  pixel cover photo.
    attr_accessor :cover_photo_small

    # Deprecated. Prefer to use activity_types.
    attr_accessor :sport_type

    # The activity types that count for a club. This takes precedence over sport_type.
    attr_accessor :activity_types

    # The club's city.
    attr_accessor :city

    # The club's state or geographical region.
    attr_accessor :state

    # The club's country.
    attr_accessor :country

    # Whether the club is private.
    attr_accessor :private

    # The club's member count.
    attr_accessor :member_count

    # Whether the club is featured or not.
    attr_accessor :featured

    # Whether the club is verified or not.
    attr_accessor :verified

    # The club's vanity URL.
    attr_accessor :url

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'resource_state' => :'resource_state',
        :'name' => :'name',
        :'profile_medium' => :'profile_medium',
        :'cover_photo' => :'cover_photo',
        :'cover_photo_small' => :'cover_photo_small',
        :'sport_type' => :'sport_type',
        :'activity_types' => :'activity_types',
        :'city' => :'city',
        :'state' => :'state',
        :'country' => :'country',
        :'private' => :'private',
        :'member_count' => :'member_count',
        :'featured' => :'featured',
        :'verified' => :'verified',
        :'url' => :'url'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'Integer',
        :'resource_state' => :'Integer',
        :'name' => :'String',
        :'profile_medium' => :'String',
        :'cover_photo' => :'String',
        :'cover_photo_small' => :'String',
        :'sport_type' => :'String',
        :'activity_types' => :'Array<ActivityType>',
        :'city' => :'String',
        :'state' => :'String',
        :'country' => :'String',
        :'private' => :'Boolean',
        :'member_count' => :'Integer',
        :'featured' => :'Boolean',
        :'verified' => :'Boolean',
        :'url' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # List of class defined in allOf (OpenAPI v3)
    def self.openapi_all_of
      [
      :'MetaClub'
      ]
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `StravaClient::SummaryClub` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `StravaClient::SummaryClub`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'resource_state')
        self.resource_state = attributes[:'resource_state']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'profile_medium')
        self.profile_medium = attributes[:'profile_medium']
      end

      if attributes.key?(:'cover_photo')
        self.cover_photo = attributes[:'cover_photo']
      end

      if attributes.key?(:'cover_photo_small')
        self.cover_photo_small = attributes[:'cover_photo_small']
      end

      if attributes.key?(:'sport_type')
        self.sport_type = attributes[:'sport_type']
      end

      if attributes.key?(:'activity_types')
        if (value = attributes[:'activity_types']).is_a?(Array)
          self.activity_types = value
        end
      end

      if attributes.key?(:'city')
        self.city = attributes[:'city']
      end

      if attributes.key?(:'state')
        self.state = attributes[:'state']
      end

      if attributes.key?(:'country')
        self.country = attributes[:'country']
      end

      if attributes.key?(:'private')
        self.private = attributes[:'private']
      end

      if attributes.key?(:'member_count')
        self.member_count = attributes[:'member_count']
      end

      if attributes.key?(:'featured')
        self.featured = attributes[:'featured']
      end

      if attributes.key?(:'verified')
        self.verified = attributes[:'verified']
      end

      if attributes.key?(:'url')
        self.url = attributes[:'url']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      sport_type_validator = EnumAttributeValidator.new('String', ["cycling", "running", "triathlon", "other"])
      return false unless sport_type_validator.valid?(@sport_type)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] sport_type Object to be assigned
    def sport_type=(sport_type)
      validator = EnumAttributeValidator.new('String', ["cycling", "running", "triathlon", "other"])
      unless validator.valid?(sport_type)
        fail ArgumentError, "invalid value for \"sport_type\", must be one of #{validator.allowable_values}."
      end
      @sport_type = sport_type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          resource_state == o.resource_state &&
          name == o.name &&
          profile_medium == o.profile_medium &&
          cover_photo == o.cover_photo &&
          cover_photo_small == o.cover_photo_small &&
          sport_type == o.sport_type &&
          activity_types == o.activity_types &&
          city == o.city &&
          state == o.state &&
          country == o.country &&
          private == o.private &&
          member_count == o.member_count &&
          featured == o.featured &&
          verified == o.verified &&
          url == o.url
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, resource_state, name, profile_medium, cover_photo, cover_photo_small, sport_type, activity_types, city, state, country, private, member_count, featured, verified, url].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = StravaClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
