=begin
#Strava API v3

#The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.

The version of the OpenAPI document: 3.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'date'
require 'time'

module StravaClient
  class SummaryActivity
    # The unique identifier of the activity
    attr_accessor :id

    # The identifier provided at upload time
    attr_accessor :external_id

    # The identifier of the upload that resulted in this activity
    attr_accessor :upload_id

    attr_accessor :athlete

    # The name of the activity
    attr_accessor :name

    # The activity's distance, in meters
    attr_accessor :distance

    # The activity's moving time, in seconds
    attr_accessor :moving_time

    # The activity's elapsed time, in seconds
    attr_accessor :elapsed_time

    # The activity's total elevation gain.
    attr_accessor :total_elevation_gain

    # The activity's highest elevation, in meters
    attr_accessor :elev_high

    # The activity's lowest elevation, in meters
    attr_accessor :elev_low

    attr_accessor :type

    attr_accessor :sport_type

    # The time at which the activity was started.
    attr_accessor :start_date

    # The time at which the activity was started in the local timezone.
    attr_accessor :start_date_local

    # The timezone of the activity
    attr_accessor :timezone

    # A pair of latitude/longitude coordinates, represented as an array of 2 floating point numbers.
    attr_accessor :start_latlng

    # A pair of latitude/longitude coordinates, represented as an array of 2 floating point numbers.
    attr_accessor :end_latlng

    # The number of achievements gained during this activity
    attr_accessor :achievement_count

    # The number of kudos given for this activity
    attr_accessor :kudos_count

    # The number of comments for this activity
    attr_accessor :comment_count

    # The number of athletes for taking part in a group activity
    attr_accessor :athlete_count

    # The number of Instagram photos for this activity
    attr_accessor :photo_count

    # The number of Instagram and Strava photos for this activity
    attr_accessor :total_photo_count

    attr_accessor :map

    # Whether this activity was recorded on a training machine
    attr_accessor :trainer

    # Whether this activity is a commute
    attr_accessor :commute

    # Whether this activity was created manually
    attr_accessor :manual

    # Whether this activity is private
    attr_accessor :private

    # Whether this activity is flagged
    attr_accessor :flagged

    # The activity's workout type
    attr_accessor :workout_type

    # The unique identifier of the upload in string format
    attr_accessor :upload_id_str

    # The activity's average speed, in meters per second
    attr_accessor :average_speed

    # The activity's max speed, in meters per second
    attr_accessor :max_speed

    # Whether the logged-in athlete has kudoed this activity
    attr_accessor :has_kudoed

    # Whether the activity is muted
    attr_accessor :hide_from_home

    # The id of the gear for the activity
    attr_accessor :gear_id

    # The total work done in kilojoules during this activity. Rides only
    attr_accessor :kilojoules

    # Average power output in watts during this activity. Rides only
    attr_accessor :average_watts

    # Whether the watts are from a power meter, false if estimated
    attr_accessor :device_watts

    # Rides with power meter data only
    attr_accessor :max_watts

    # Similar to Normalized Power. Rides with power meter data only
    attr_accessor :weighted_average_watts

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'external_id' => :'external_id',
        :'upload_id' => :'upload_id',
        :'athlete' => :'athlete',
        :'name' => :'name',
        :'distance' => :'distance',
        :'moving_time' => :'moving_time',
        :'elapsed_time' => :'elapsed_time',
        :'total_elevation_gain' => :'total_elevation_gain',
        :'elev_high' => :'elev_high',
        :'elev_low' => :'elev_low',
        :'type' => :'type',
        :'sport_type' => :'sport_type',
        :'start_date' => :'start_date',
        :'start_date_local' => :'start_date_local',
        :'timezone' => :'timezone',
        :'start_latlng' => :'start_latlng',
        :'end_latlng' => :'end_latlng',
        :'achievement_count' => :'achievement_count',
        :'kudos_count' => :'kudos_count',
        :'comment_count' => :'comment_count',
        :'athlete_count' => :'athlete_count',
        :'photo_count' => :'photo_count',
        :'total_photo_count' => :'total_photo_count',
        :'map' => :'map',
        :'trainer' => :'trainer',
        :'commute' => :'commute',
        :'manual' => :'manual',
        :'private' => :'private',
        :'flagged' => :'flagged',
        :'workout_type' => :'workout_type',
        :'upload_id_str' => :'upload_id_str',
        :'average_speed' => :'average_speed',
        :'max_speed' => :'max_speed',
        :'has_kudoed' => :'has_kudoed',
        :'hide_from_home' => :'hide_from_home',
        :'gear_id' => :'gear_id',
        :'kilojoules' => :'kilojoules',
        :'average_watts' => :'average_watts',
        :'device_watts' => :'device_watts',
        :'max_watts' => :'max_watts',
        :'weighted_average_watts' => :'weighted_average_watts'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'Integer',
        :'external_id' => :'String',
        :'upload_id' => :'Integer',
        :'athlete' => :'MetaAthlete',
        :'name' => :'String',
        :'distance' => :'Float',
        :'moving_time' => :'Integer',
        :'elapsed_time' => :'Integer',
        :'total_elevation_gain' => :'Float',
        :'elev_high' => :'Float',
        :'elev_low' => :'Float',
        :'type' => :'ActivityType',
        :'sport_type' => :'SportType',
        :'start_date' => :'Time',
        :'start_date_local' => :'Time',
        :'timezone' => :'String',
        :'start_latlng' => :'Array<Float>',
        :'end_latlng' => :'Array<Float>',
        :'achievement_count' => :'Integer',
        :'kudos_count' => :'Integer',
        :'comment_count' => :'Integer',
        :'athlete_count' => :'Integer',
        :'photo_count' => :'Integer',
        :'total_photo_count' => :'Integer',
        :'map' => :'PolylineMap',
        :'trainer' => :'Boolean',
        :'commute' => :'Boolean',
        :'manual' => :'Boolean',
        :'private' => :'Boolean',
        :'flagged' => :'Boolean',
        :'workout_type' => :'Integer',
        :'upload_id_str' => :'String',
        :'average_speed' => :'Float',
        :'max_speed' => :'Float',
        :'has_kudoed' => :'Boolean',
        :'hide_from_home' => :'Boolean',
        :'gear_id' => :'String',
        :'kilojoules' => :'Float',
        :'average_watts' => :'Float',
        :'device_watts' => :'Boolean',
        :'max_watts' => :'Integer',
        :'weighted_average_watts' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # List of class defined in allOf (OpenAPI v3)
    def self.openapi_all_of
      [
      :'MetaActivity'
      ]
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `StravaClient::SummaryActivity` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `StravaClient::SummaryActivity`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'external_id')
        self.external_id = attributes[:'external_id']
      end

      if attributes.key?(:'upload_id')
        self.upload_id = attributes[:'upload_id']
      end

      if attributes.key?(:'athlete')
        self.athlete = attributes[:'athlete']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'distance')
        self.distance = attributes[:'distance']
      end

      if attributes.key?(:'moving_time')
        self.moving_time = attributes[:'moving_time']
      end

      if attributes.key?(:'elapsed_time')
        self.elapsed_time = attributes[:'elapsed_time']
      end

      if attributes.key?(:'total_elevation_gain')
        self.total_elevation_gain = attributes[:'total_elevation_gain']
      end

      if attributes.key?(:'elev_high')
        self.elev_high = attributes[:'elev_high']
      end

      if attributes.key?(:'elev_low')
        self.elev_low = attributes[:'elev_low']
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      end

      if attributes.key?(:'sport_type')
        self.sport_type = attributes[:'sport_type']
      end

      if attributes.key?(:'start_date')
        self.start_date = attributes[:'start_date']
      end

      if attributes.key?(:'start_date_local')
        self.start_date_local = attributes[:'start_date_local']
      end

      if attributes.key?(:'timezone')
        self.timezone = attributes[:'timezone']
      end

      if attributes.key?(:'start_latlng')
        if (value = attributes[:'start_latlng']).is_a?(Array)
          self.start_latlng = value
        end
      end

      if attributes.key?(:'end_latlng')
        if (value = attributes[:'end_latlng']).is_a?(Array)
          self.end_latlng = value
        end
      end

      if attributes.key?(:'achievement_count')
        self.achievement_count = attributes[:'achievement_count']
      end

      if attributes.key?(:'kudos_count')
        self.kudos_count = attributes[:'kudos_count']
      end

      if attributes.key?(:'comment_count')
        self.comment_count = attributes[:'comment_count']
      end

      if attributes.key?(:'athlete_count')
        self.athlete_count = attributes[:'athlete_count']
      end

      if attributes.key?(:'photo_count')
        self.photo_count = attributes[:'photo_count']
      end

      if attributes.key?(:'total_photo_count')
        self.total_photo_count = attributes[:'total_photo_count']
      end

      if attributes.key?(:'map')
        self.map = attributes[:'map']
      end

      if attributes.key?(:'trainer')
        self.trainer = attributes[:'trainer']
      end

      if attributes.key?(:'commute')
        self.commute = attributes[:'commute']
      end

      if attributes.key?(:'manual')
        self.manual = attributes[:'manual']
      end

      if attributes.key?(:'private')
        self.private = attributes[:'private']
      end

      if attributes.key?(:'flagged')
        self.flagged = attributes[:'flagged']
      end

      if attributes.key?(:'workout_type')
        self.workout_type = attributes[:'workout_type']
      end

      if attributes.key?(:'upload_id_str')
        self.upload_id_str = attributes[:'upload_id_str']
      end

      if attributes.key?(:'average_speed')
        self.average_speed = attributes[:'average_speed']
      end

      if attributes.key?(:'max_speed')
        self.max_speed = attributes[:'max_speed']
      end

      if attributes.key?(:'has_kudoed')
        self.has_kudoed = attributes[:'has_kudoed']
      end

      if attributes.key?(:'hide_from_home')
        self.hide_from_home = attributes[:'hide_from_home']
      end

      if attributes.key?(:'gear_id')
        self.gear_id = attributes[:'gear_id']
      end

      if attributes.key?(:'kilojoules')
        self.kilojoules = attributes[:'kilojoules']
      end

      if attributes.key?(:'average_watts')
        self.average_watts = attributes[:'average_watts']
      end

      if attributes.key?(:'device_watts')
        self.device_watts = attributes[:'device_watts']
      end

      if attributes.key?(:'max_watts')
        self.max_watts = attributes[:'max_watts']
      end

      if attributes.key?(:'weighted_average_watts')
        self.weighted_average_watts = attributes[:'weighted_average_watts']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@start_latlng.nil? && @start_latlng.length > 2
        invalid_properties.push('invalid value for "start_latlng", number of items must be less than or equal to 2.')
      end

      if !@start_latlng.nil? && @start_latlng.length < 2
        invalid_properties.push('invalid value for "start_latlng", number of items must be greater than or equal to 2.')
      end

      if !@end_latlng.nil? && @end_latlng.length > 2
        invalid_properties.push('invalid value for "end_latlng", number of items must be less than or equal to 2.')
      end

      if !@end_latlng.nil? && @end_latlng.length < 2
        invalid_properties.push('invalid value for "end_latlng", number of items must be greater than or equal to 2.')
      end

      if !@athlete_count.nil? && @athlete_count < 1
        invalid_properties.push('invalid value for "athlete_count", must be greater than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@start_latlng.nil? && @start_latlng.length > 2
      return false if !@start_latlng.nil? && @start_latlng.length < 2
      return false if !@end_latlng.nil? && @end_latlng.length > 2
      return false if !@end_latlng.nil? && @end_latlng.length < 2
      return false if !@athlete_count.nil? && @athlete_count < 1
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] start_latlng Value to be assigned
    def start_latlng=(start_latlng)
      if start_latlng.nil?
        fail ArgumentError, 'start_latlng cannot be nil'
      end

      if start_latlng.length > 2
        fail ArgumentError, 'invalid value for "start_latlng", number of items must be less than or equal to 2.'
      end

      if start_latlng.length < 2
        fail ArgumentError, 'invalid value for "start_latlng", number of items must be greater than or equal to 2.'
      end

      @start_latlng = start_latlng
    end

    # Custom attribute writer method with validation
    # @param [Object] end_latlng Value to be assigned
    def end_latlng=(end_latlng)
      if end_latlng.nil?
        fail ArgumentError, 'end_latlng cannot be nil'
      end

      if end_latlng.length > 2
        fail ArgumentError, 'invalid value for "end_latlng", number of items must be less than or equal to 2.'
      end

      if end_latlng.length < 2
        fail ArgumentError, 'invalid value for "end_latlng", number of items must be greater than or equal to 2.'
      end

      @end_latlng = end_latlng
    end

    # Custom attribute writer method with validation
    # @param [Object] athlete_count Value to be assigned
    def athlete_count=(athlete_count)
      if athlete_count.nil?
        fail ArgumentError, 'athlete_count cannot be nil'
      end

      if athlete_count < 1
        fail ArgumentError, 'invalid value for "athlete_count", must be greater than or equal to 1.'
      end

      @athlete_count = athlete_count
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          external_id == o.external_id &&
          upload_id == o.upload_id &&
          athlete == o.athlete &&
          name == o.name &&
          distance == o.distance &&
          moving_time == o.moving_time &&
          elapsed_time == o.elapsed_time &&
          total_elevation_gain == o.total_elevation_gain &&
          elev_high == o.elev_high &&
          elev_low == o.elev_low &&
          type == o.type &&
          sport_type == o.sport_type &&
          start_date == o.start_date &&
          start_date_local == o.start_date_local &&
          timezone == o.timezone &&
          start_latlng == o.start_latlng &&
          end_latlng == o.end_latlng &&
          achievement_count == o.achievement_count &&
          kudos_count == o.kudos_count &&
          comment_count == o.comment_count &&
          athlete_count == o.athlete_count &&
          photo_count == o.photo_count &&
          total_photo_count == o.total_photo_count &&
          map == o.map &&
          trainer == o.trainer &&
          commute == o.commute &&
          manual == o.manual &&
          private == o.private &&
          flagged == o.flagged &&
          workout_type == o.workout_type &&
          upload_id_str == o.upload_id_str &&
          average_speed == o.average_speed &&
          max_speed == o.max_speed &&
          has_kudoed == o.has_kudoed &&
          hide_from_home == o.hide_from_home &&
          gear_id == o.gear_id &&
          kilojoules == o.kilojoules &&
          average_watts == o.average_watts &&
          device_watts == o.device_watts &&
          max_watts == o.max_watts &&
          weighted_average_watts == o.weighted_average_watts
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, external_id, upload_id, athlete, name, distance, moving_time, elapsed_time, total_elevation_gain, elev_high, elev_low, type, sport_type, start_date, start_date_local, timezone, start_latlng, end_latlng, achievement_count, kudos_count, comment_count, athlete_count, photo_count, total_photo_count, map, trainer, commute, manual, private, flagged, workout_type, upload_id_str, average_speed, max_speed, has_kudoed, hide_from_home, gear_id, kilojoules, average_watts, device_watts, max_watts, weighted_average_watts].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = StravaClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
