=begin
#Strava API v3

#The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.

The version of the OpenAPI document: 3.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'date'
require 'time'

module StravaClient
  class Waypoint
    # A pair of latitude/longitude coordinates, represented as an array of 2 floating point numbers.
    attr_accessor :latlng

    # A pair of latitude/longitude coordinates, represented as an array of 2 floating point numbers.
    attr_accessor :target_latlng

    # Categories that the waypoint belongs to
    attr_accessor :categories

    # A title for the waypoint
    attr_accessor :title

    # A description of the waypoint (optional)
    attr_accessor :description

    # The number meters along the route that the waypoint is located
    attr_accessor :distance_into_route

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'latlng' => :'latlng',
        :'target_latlng' => :'target_latlng',
        :'categories' => :'categories',
        :'title' => :'title',
        :'description' => :'description',
        :'distance_into_route' => :'distance_into_route'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'latlng' => :'Array<Float>',
        :'target_latlng' => :'Array<Float>',
        :'categories' => :'Array<String>',
        :'title' => :'String',
        :'description' => :'String',
        :'distance_into_route' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `StravaClient::Waypoint` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `StravaClient::Waypoint`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'latlng')
        if (value = attributes[:'latlng']).is_a?(Array)
          self.latlng = value
        end
      end

      if attributes.key?(:'target_latlng')
        if (value = attributes[:'target_latlng']).is_a?(Array)
          self.target_latlng = value
        end
      end

      if attributes.key?(:'categories')
        if (value = attributes[:'categories']).is_a?(Array)
          self.categories = value
        end
      end

      if attributes.key?(:'title')
        self.title = attributes[:'title']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'distance_into_route')
        self.distance_into_route = attributes[:'distance_into_route']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@latlng.nil? && @latlng.length > 2
        invalid_properties.push('invalid value for "latlng", number of items must be less than or equal to 2.')
      end

      if !@latlng.nil? && @latlng.length < 2
        invalid_properties.push('invalid value for "latlng", number of items must be greater than or equal to 2.')
      end

      if !@target_latlng.nil? && @target_latlng.length > 2
        invalid_properties.push('invalid value for "target_latlng", number of items must be less than or equal to 2.')
      end

      if !@target_latlng.nil? && @target_latlng.length < 2
        invalid_properties.push('invalid value for "target_latlng", number of items must be greater than or equal to 2.')
      end

      if !@categories.nil? && @categories.length < 0
        invalid_properties.push('invalid value for "categories", number of items must be greater than or equal to 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@latlng.nil? && @latlng.length > 2
      return false if !@latlng.nil? && @latlng.length < 2
      return false if !@target_latlng.nil? && @target_latlng.length > 2
      return false if !@target_latlng.nil? && @target_latlng.length < 2
      return false if !@categories.nil? && @categories.length < 0
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] latlng Value to be assigned
    def latlng=(latlng)
      if latlng.nil?
        fail ArgumentError, 'latlng cannot be nil'
      end

      if latlng.length > 2
        fail ArgumentError, 'invalid value for "latlng", number of items must be less than or equal to 2.'
      end

      if latlng.length < 2
        fail ArgumentError, 'invalid value for "latlng", number of items must be greater than or equal to 2.'
      end

      @latlng = latlng
    end

    # Custom attribute writer method with validation
    # @param [Object] target_latlng Value to be assigned
    def target_latlng=(target_latlng)
      if target_latlng.nil?
        fail ArgumentError, 'target_latlng cannot be nil'
      end

      if target_latlng.length > 2
        fail ArgumentError, 'invalid value for "target_latlng", number of items must be less than or equal to 2.'
      end

      if target_latlng.length < 2
        fail ArgumentError, 'invalid value for "target_latlng", number of items must be greater than or equal to 2.'
      end

      @target_latlng = target_latlng
    end

    # Custom attribute writer method with validation
    # @param [Object] categories Value to be assigned
    def categories=(categories)
      if categories.nil?
        fail ArgumentError, 'categories cannot be nil'
      end

      if categories.length < 0
        fail ArgumentError, 'invalid value for "categories", number of items must be greater than or equal to 0.'
      end

      @categories = categories
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          latlng == o.latlng &&
          target_latlng == o.target_latlng &&
          categories == o.categories &&
          title == o.title &&
          description == o.description &&
          distance_into_route == o.distance_into_route
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [latlng, target_latlng, categories, title, description, distance_into_route].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = StravaClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
